project:
  type: website
  output-dir: docs

website:
  description: "大老李聊数学的个人博客"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "大老李聊数学"
  navbar:
    right:
      - about.qmd
      - text: 知乎
        href: https://www.zhihu.com/people/li-you-hua
      - text: bilibili
        href: https://space.bilibili.com/423722633
format:
  html:
    theme:
      - cosmos
    css: styles.css
