---
title: '从无理数中算出整数--形形色色的“近整数”'
date: "2019-08-06"
categories:
  - "每周一题"
---

从无理数中算出整数–形形色色的“近整数”

大家好，我是大老李。今天聊一个比较轻松的话题–“近整数”，Almost Integer。“近整数”的概念非常简单，就是一些从无理数的运算组合中，不经意发现一些计算结果非常接近整数的情况，所以叫近整数。

之前的节目中，大老李提到过一个近整数，就是在有关“黑格纳数163”那期节目。我提到了这样一个数字：<span class="katex--inline"><span class="katex"><span class="katex-mathml">eπ163e^{\pi \sqrt{163}}</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.00199em;vertical-align:0;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:1.00199em;"><span class="" style="top:-3.063em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span><span class="mord sqrt mtight"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.912845em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord mtight" style="padding-left:.833em;"><span class="mord mtight">1</span><span class="mord mtight">6</span><span class="mord mtight">3</span></span></span><span class="" style="top:-2.87285em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail mtight" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.127155em;"><span class=""></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></span>。

因为<span class="katex--inline"><span class="katex"><span class="katex-mathml">ee</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span class="mord mathdefault">e</span></span></span></span></span>, <span class="katex--inline"><span class="katex"><span class="katex-mathml">π\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>和<span class="katex--inline"><span class="katex"><span class="katex-mathml">163\sqrt{163}</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.04em;vertical-align:-.13278em;"></span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.90722em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord" style="padding-left:.833em;"><span class="mord">1</span><span class="mord">6</span><span class="mord">3</span></span></span><span class="" style="top:-2.86722em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.13278em;"><span class=""></span></span></span></span></span></span></span></span></span>都是无理数，所以这个数字的计算结果直觉中当然是一个无理数，这是对的。但是这个无理数是如此接近于整数，以至于大老李第一次看到的时候惊得下巴都快掉下来了。当然，你用计算器是算不出这个数字的小数部分了，因为它的整数部分已经非常大了，但我十分建议你自己上网找些大数字计算器，看看这个数字的样子：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">eπ163=262537412640768743.99999999999925007...e^{\pi \sqrt{163}}=262537412640768743.99999999999925007...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.05199em;vertical-align:0;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:1.05199em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span><span class="mord sqrt mtight"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.912845em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord mtight" style="padding-left:.833em;"><span class="mord mtight">1</span><span class="mord mtight">6</span><span class="mord mtight">3</span></span></span><span class="" style="top:-2.87285em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail mtight" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.127155em;"><span class=""></span></span></span></span></span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">2</span><span class="mord">6</span><span class="mord">2</span><span class="mord">5</span><span class="mord">3</span><span class="mord">7</span><span class="mord">4</span><span class="mord">1</span><span class="mord">2</span><span class="mord">6</span><span class="mord">4</span><span class="mord">0</span><span class="mord">7</span><span class="mord">6</span><span class="mord">8</span><span class="mord">7</span><span class="mord">4</span><span class="mord">3</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">2</span><span class="mord">5</span><span class="mord">0</span><span class="mord">0</span><span class="mord">7</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

其小数点后有12个9，你就知道它是多么接近于整数。当然最令人吃惊的是通过<span class="katex--inline"><span class="katex"><span class="katex-mathml">ee</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span class="mord mathdefault">e</span></span></span></span></span>, <span class="katex--inline"><span class="katex"><span class="katex-mathml">π\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>和<span class="katex--inline"><span class="katex"><span class="katex-mathml">163\sqrt{163}</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.04em;vertical-align:-.13278em;"></span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.90722em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord" style="padding-left:.833em;"><span class="mord">1</span><span class="mord">6</span><span class="mord">3</span></span></span><span class="" style="top:-2.86722em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.13278em;"><span class=""></span></span></span></span></span></span></span></span></span>这些无理数的简单组合，能计算出这样一个如此接近整数的数。当然这个数字如此解近整数是有原因的，具体原因还是请听黑格纳数那期节目，而且我们知道根号里的163换成其他任何整数都不会使结果更加接近整数了。所以这个形式简单的数字里蕴含了很深的数学含义，这就是我们研究近整数的原因之一。

以下大老李给大家介绍一些其他的近整数，它们的共同特点就是都是从无理数包括超越数的组合中得到的一些非常接近整数的无理数。另外，要注意一点，近整数是与进制无关的，不管是10进制，16进制，或者二进制下，这些数字都还是近整数，所以外星人也可能在研究这些数字。

首先一组近整数是黄金分割比的幂次。黄金分割就是<span class="katex--inline"><span class="katex"><span class="katex-mathml">(1+5)/2(1+\sqrt{5})/2</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mopen">(</span><span class="mord">1</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:1.15722em;vertical-align:-.25em;"></span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.90722em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord" style="padding-left:.833em;"><span class="mord">5</span></span></span><span class="" style="top:-2.86722em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.13278em;"><span class=""></span></span></span></span></span><span class="mclose">)</span><span class="mord">/</span><span class="mord">2</span></span></span></span></span>，约等于1.618。这个数字的幂次会越来越接近整数，比如它的17，18，19次方：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">ϕ17=3571+159752≈3571.00028\phi^{17}=\frac{3571+1597\sqrt{5}}{2}\approx 3571.00028</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.05855em;vertical-align:-.19444em;"></span><span class="mord"><span class="mord mathdefault">ϕ</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.864108em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1</span><span class="mord mtight">7</span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:2.27022em;vertical-align:-.686em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.58422em;"><span class="" style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">2</span></span></span><span class="" style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:.04em;"></span></span><span class="" style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">3</span><span class="mord">5</span><span class="mord">7</span><span class="mord">1</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mord">1</span><span class="mord">5</span><span class="mord">9</span><span class="mord">7</span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.90722em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord" style="padding-left:.833em;"><span class="mord">5</span></span></span><span class="" style="top:-2.86722em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.13278em;"><span class=""></span></span></span></span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.686em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">≈</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">3</span><span class="mord">5</span><span class="mord">7</span><span class="mord">1</span><span class="mord">.</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">2</span><span class="mord">8</span></span></span></span></span></span>

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">ϕ18=2889+12925≈5777.999827\phi^{18}=2889+1292\sqrt{5}\approx 5777.999827</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.05855em;vertical-align:-.19444em;"></span><span class="mord"><span class="mord mathdefault">ϕ</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.864108em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1</span><span class="mord mtight">8</span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.72777em;vertical-align:-.08333em;"></span><span class="mord">2</span><span class="mord">8</span><span class="mord">8</span><span class="mord">9</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:1.04em;vertical-align:-.083905em;"></span><span class="mord">1</span><span class="mord">2</span><span class="mord">9</span><span class="mord">2</span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.956095em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord" style="padding-left:.833em;"><span class="mord">5</span></span></span><span class="" style="top:-2.9161em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.083905em;"><span class=""></span></span></span></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">≈</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">5</span><span class="mord">7</span><span class="mord">7</span><span class="mord">7</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">8</span><span class="mord">2</span><span class="mord">7</span></span></span></span></span></span>

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">ϕ19=9349+418152≈9349.000107\phi^{19}=\frac{9349+4181\sqrt{5}}{2}\approx 9349.000107</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.05855em;vertical-align:-.19444em;"></span><span class="mord"><span class="mord mathdefault">ϕ</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.864108em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1</span><span class="mord mtight">9</span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:2.27022em;vertical-align:-.686em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.58422em;"><span class="" style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">2</span></span></span><span class="" style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:.04em;"></span></span><span class="" style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">9</span><span class="mord">3</span><span class="mord">4</span><span class="mord">9</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mord">4</span><span class="mord">1</span><span class="mord">8</span><span class="mord">1</span><span class="mord sqrt"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.90722em;"><span class="svg-align" style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord" style="padding-left:.833em;"><span class="mord">5</span></span></span><span class="" style="top:-2.86722em;"><span class="pstrut" style="height:3em;"></span><span class="hide-tail" style="min-width:.853em;height:1.08em;"></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.13278em;"><span class=""></span></span></span></span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.686em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">≈</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">9</span><span class="mord">3</span><span class="mord">4</span><span class="mord">9</span><span class="mord">.</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">1</span><span class="mord">0</span><span class="mord">7</span></span></span></span></span></span>

这其实是原因的，因为黄金分割比属于无理数里比较特别的一种称为PV数，这种数字在“三维世界的黄金比例-塑料常数”中也提到过，请大家自行查阅。

下一个近整数是<span class="katex--inline"><span class="katex"><span class="katex-mathml">sin⁡(11)\sin(11)</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mop">sin</span><span class="mopen">(</span><span class="mord">1</span><span class="mord">1</span><span class="mclose">)</span></span></span></span></span>，这里的11是弧度制下的11，不是11°。如果你手头有科学计算器可以马上算一下，你会发现：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">sin⁡11≈−0.999990206...\sin11\approx-0.999990206...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.66786em;vertical-align:0;"></span><span class="mop">sin</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">1</span><span class="mord">1</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">≈</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.72777em;vertical-align:-.08333em;"></span><span class="mord">−</span><span class="mord">0</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">0</span><span class="mord">2</span><span class="mord">0</span><span class="mord">6</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

它为什么如此接近-1？其实道理不难。因为我们知道22/7是pi的一个近似分数，那么：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">cos⁡22≈cos⁡(7π)=−1\cos22\approx \cos(7\pi)=-1</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mop">cos</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">2</span><span class="mord">2</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">≈</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mop">cos</span><span class="mopen">(</span><span class="mord">7</span><span style="margin-right:.03588em;" class="mord mathdefault">π</span><span class="mclose">)</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.72777em;vertical-align:-.08333em;"></span><span class="mord">−</span><span class="mord">1</span></span></span></span></span></span>

知道<span class="katex--inline"><span class="katex"><span class="katex-mathml">cos⁡22\cos22</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mop">cos</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">2</span><span class="mord">2</span></span></span></span></span>约等于-1，那么 <span class="katex--inline"><span class="katex"><span class="katex-mathml">sin⁡(11)\sin (11)</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mop">sin</span><span class="mopen">(</span><span class="mord">1</span><span class="mord">1</span><span class="mclose">)</span></span></span></span></span>约等于-1就一点不奇怪了。

当然，你还可以用<span class="katex--inline"><span class="katex"><span class="katex-mathml">π\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>更好的近似分数构造这种类型的近整数，比如355/113。这个就留个听众自行尝试了。

下一个例子是非常让人震惊的一个例子，有另一个有关<span class="katex--inline"><span class="katex"><span class="katex-mathml">ee</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span class="mord mathdefault">e</span></span></span></span></span>和<span class="katex--inline"><span class="katex"><span class="katex-mathml">π\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>的近整数：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">eπ−π=19.999099979...e^{\pi}-\pi=19.999099979...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.797722em;vertical-align:-.08333em;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.714392em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">1</span><span class="mord">9</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">0</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">7</span><span class="mord">9</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

这个近整数是1988年，几乎有三位数学家尼尔斯·洛恩，约翰·康威和西蒙·普劳夫同时发现的。上一期说过<span class="katex--inline"><span class="katex"><span class="katex-mathml">eπe^{\pi}</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.664392em;vertical-align:0;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.664392em;"><span class="" style="top:-3.063em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span></span></span></span></span></span></span></span></span></span></span></span></span>是为数不多的几个被证明的超越数，它现在被称为“盖尔方德常数。”而<span class="katex--inline"><span class="katex"><span class="katex-mathml">eπ−πe^{\pi}-\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.747722em;vertical-align:-.08333em;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.664392em;"><span class="" style="top:-3.063em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>是一个近整数，这说明<span class="katex--inline"><span class="katex"><span class="katex-mathml">eπe^\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.664392em;vertical-align:0;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.664392em;"><span class="" style="top:-3.063em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span></span></span></span></span></span></span></span></span></span></span></span>的小数部分非常接近pi的小数部分，但这是为什么，至今没有人给出令人满意的解释，可以说是数学中的神秘现象。

下一个近整数比较搞笑：是很多cos余弦的嵌套：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">2cos⁡(cos⁡(cos⁡(cos⁡(cos⁡(cos⁡(cos⁡(5)))))))=0.99999525497000...2\cos(\cos(\cos(\cos(\cos(\cos(\cos(5)))))))=0.99999525497000...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mord">2</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mop">cos</span><span class="mopen">(</span><span class="mop">cos</span><span class="mopen">(</span><span class="mop">cos</span><span class="mopen">(</span><span class="mop">cos</span><span class="mopen">(</span><span class="mop">cos</span><span class="mopen">(</span><span class="mop">cos</span><span class="mopen">(</span><span class="mop">cos</span><span class="mopen">(</span><span class="mord">5</span><span class="mclose">)</span><span class="mclose">)</span><span class="mclose">)</span><span class="mclose">)</span><span class="mclose">)</span><span class="mclose">)</span><span class="mclose">)</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">0</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">5</span><span class="mord">2</span><span class="mord">5</span><span class="mord">4</span><span class="mord">9</span><span class="mord">7</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

我很怀疑这个数字是发现者无聊按计算器算出来的。现在的问题是为什么这个数字是近整数？以上cos再多一层不行，5换成4或6也不行。这是数字里的又一个神秘现象。

下一个近整数是拉马努金发现的：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">22π4=2143+2.748...×10−622\pi^{4}=2143+2.748...\times 10^{-6}</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.864108em;vertical-align:0;"></span><span class="mord">2</span><span class="mord">2</span><span class="mord"><span style="margin-right:.03588em;" class="mord mathdefault">π</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.864108em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">4</span></span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.72777em;vertical-align:-.08333em;"></span><span class="mord">2</span><span class="mord">1</span><span class="mord">4</span><span class="mord">3</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:.72777em;vertical-align:-.08333em;"></span><span class="mord">2</span><span class="mord">.</span><span class="mord">7</span><span class="mord">4</span><span class="mord">8</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">×</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:.864108em;vertical-align:0;"></span><span class="mord">1</span><span class="mord"><span class="mord">0</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.864108em;"><span class="" style="top:-3.113em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">−</span><span class="mord mtight">6</span></span></span></span></span></span></span></span></span></span></span></span></span></span>

这个数字很有拉马努金风格。

有些近整数是含有对数的：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">510log⁡107=431.00000040...510\log_{10}7=431.00000040...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.93858em;vertical-align:-.24414em;"></span><span class="mord">5</span><span class="mord">1</span><span class="mord">0</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mop"><span class="mop">lo<span style="margin-right:.01389em;">g</span></span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.206968em;"><span class="" style="top:-2.45586em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">1</span><span class="mord mtight">0</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.24414em;"><span class=""></span></span></span></span></span></span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">7</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">4</span><span class="mord">3</span><span class="mord">1</span><span class="mord">.</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">4</span><span class="mord">0</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">88ln⁡89=395.00000053...88\ln89=395.00000053...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.69444em;vertical-align:0;"></span><span class="mord">8</span><span class="mord">8</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mop">ln</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">8</span><span class="mord">9</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">3</span><span class="mord">9</span><span class="mord">5</span><span class="mord">.</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">5</span><span class="mord">3</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">272log⁡π97=1087.000000204...272\log_{\pi}97=1087.000000204...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.93858em;vertical-align:-.24414em;"></span><span class="mord">2</span><span class="mord">7</span><span class="mord">2</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mop"><span class="mop">lo<span style="margin-right:.01389em;">g</span></span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:.057252em;"><span class="" style="top:-2.45586em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.24414em;"><span class=""></span></span></span></span></span></span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">9</span><span class="mord">7</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">1</span><span class="mord">0</span><span class="mord">8</span><span class="mord">7</span><span class="mord">.</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">0</span><span class="mord">2</span><span class="mord">0</span><span class="mord">4</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

再说一些有关pi和e的近整数：比如

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">163(π−e)=68.9996644...163(\pi - e)=68.9996644...</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mord">1</span><span class="mord">6</span><span class="mord">3</span><span class="mopen">(</span><span style="margin-right:.03588em;" class="mord mathdefault">π</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mord mathdefault">e</span><span class="mclose">)</span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">6</span><span class="mord">8</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">6</span><span class="mord">6</span><span class="mord">4</span><span class="mord">4</span><span class="mord">.</span><span class="mord">.</span><span class="mord">.</span></span></span></span></span></span>

再一次出现163。也很神奇的是用<span class="katex--inline"><span class="katex"><span class="katex-mathml">π\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>去减掉<span class="katex--inline"><span class="katex"><span class="katex-mathml">ee</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span class="mord mathdefault">e</span></span></span></span></span>。因为我想象不出来任何场合需要用<span class="katex--inline"><span class="katex"><span class="katex-mathml">π−e\pi-e</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.66666em;vertical-align:-.08333em;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span class="mord mathdefault">e</span></span></span></span></span>这样的运算，但是这样结果乘以163会如此接近整数，实在是太神奇了。

还有与pi和e相关的是：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">π9e8=9.9998387\frac{\pi^9}{e^8}=9.9998387</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:2.17711em;vertical-align:-.686em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.49111em;"><span class="" style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.740108em;"><span class="" style="top:-2.989em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">8</span></span></span></span></span></span></span></span></span></span><span class="" style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:.04em;"></span></span><span class="" style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord"><span style="margin-right:.03588em;" class="mord mathdefault">π</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.814108em;"><span class="" style="top:-3.063em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">9</span></span></span></span></span></span></span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.686em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">9</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">8</span><span class="mord">3</span><span class="mord">8</span><span class="mord">7</span></span></span></span></span></span>

再来一个与163相关的 :

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">163ln⁡163=31.9999987384\frac{163}{\ln163}=31.9999987384</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:2.00744em;vertical-align:-.686em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.32144em;"><span class="" style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mop">ln</span><span class="mspace" style="margin-right:.166667em;"></span><span class="mord">1</span><span class="mord">6</span><span class="mord">3</span></span></span><span class="" style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:.04em;"></span></span><span class="" style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord">1</span><span class="mord">6</span><span class="mord">3</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.686em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:.64444em;vertical-align:0;"></span><span class="mord">3</span><span class="mord">1</span><span class="mord">.</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">9</span><span class="mord">8</span><span class="mord">7</span><span class="mord">3</span><span class="mord">8</span><span class="mord">4</span></span></span></span></span></span>

与e和pi相关的近整数非常多，我就不在节目念了。强烈推荐你关注我的公众号，“大老李聊数学”，我会发这些数字以文稿形式发送出来 ，供你欣赏。

最后，如果我们允许用物理常数进行运算的话，那么科学家也发现了一些在国际单位制下，可以得到近整数，最让人吃惊这样一个数：

<span class="katex--display"><span class="katex-display"><span class="katex"><span class="katex-mathml">cekh=1.008mA/(sK)\frac{cek}{h}=1.008mA/(sK)</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:2.05744em;vertical-align:-.686em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.37144em;"><span class="" style="top:-2.314em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord mathdefault">h</span></span></span><span class="" style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:.04em;"></span></span><span class="" style="top:-3.677em;"><span class="pstrut" style="height:3em;"></span><span class="mord"><span class="mord mathdefault">c</span><span class="mord mathdefault">e</span><span style="margin-right:.03148em;" class="mord mathdefault">k</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:.686em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right:.277778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:.277778em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-.25em;"></span><span class="mord">1</span><span class="mord">.</span><span class="mord">0</span><span class="mord">0</span><span class="mord">8</span><span class="mord mathdefault">m</span><span class="mord mathdefault">A</span><span class="mord">/</span><span class="mopen">(</span><span class="mord mathdefault">s</span><span style="margin-right:.07153em;" class="mord mathdefault">K</span><span class="mclose">)</span></span></span></span></span></span>

其中c是光速，e是单位电子电量，k是玻尔兹曼常数，h是普朗克常数。你如果将以上常数用国际单位制下的数值代入，就会发现是1.0008，单位是mA/(sK)。这些单位这么组合有什么意义吗？科学家还没有看出来。但是这个结果如此接近1是巧合还是必然？会不会是我们测量不精确，其实这个组合就应该等于1？如果这是必然，那么这些看似不太相关的常数如此组合，能得到一个整数，那么其中肯定有一个十分深刻的道理，这让人浮想联翩。

好了，近整数就讲到这里。近整数有点像数学里的物理实验 ，通过一些简单的对无理数的组合运算，不经意间得到一个非常接近整数的无理数。其中很多近整数我们能解释其接近整数的原因，还有很多我们不知道。特别是<span class="katex--inline"><span class="katex"><span class="katex-mathml">ee</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span class="mord mathdefault">e</span></span></span></span></span>和<span class="katex--inline"><span class="katex"><span class="katex-mathml">π\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>的一些组合，它们不愧为数学常数中的两大王牌，任何场合它们都不会缺席。而数学家发现包含<span class="katex--inline"><span class="katex"><span class="katex-mathml">eπe^\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.664392em;vertical-align:0;"></span><span class="mord"><span class="mord mathdefault">e</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:.664392em;"><span class="" style="top:-3.063em;margin-right:.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span style="margin-right:.03588em;" class="mord mathdefault mtight">π</span></span></span></span></span></span></span></span></span></span></span></span>和<span class="katex--inline"><span class="katex"><span class="katex-mathml">e−πe-\pi</span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:.66666em;vertical-align:-.08333em;"></span><span class="mord mathdefault">e</span><span class="mspace" style="margin-right:.222222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:.222222em;"></span></span><span class="base"><span class="strut" style="height:.43056em;vertical-align:0;"></span><span style="margin-right:.03588em;" class="mord mathdefault">π</span></span></span></span></span>的运算组合可以得到近整数的结果，这使得这两个我们最熟悉的数学常数更平添了一点神秘感。

最后，科学家还发现一些物理常数的组合能得到近整数，这是巧合还是必然？这又是一个有待人类无尽探索的问题。好了，下期再见！

参考链接：

<a href="https://en.wikipedia.org/wiki/Almost_integer">https://en.wikipedia.org/wiki/Almost_integer</a>

<a href="http://mathworld.wolfram.com/AlmostInteger.html">http://mathworld.wolfram.com/AlmostInteger.html</a>

<hr>

喜马拉雅：<a href="https://www.ximalaya.com/keji/6310606/">https://www.ximalaya.com/keji/6310606/</a>

微信关注：dalaoli_shuxue

B站: <a href="https://space.bilibili.com/423722633">https://space.bilibili.com/423722633</a>

知乎：<a href="https://zhuanlan.zhihu.com/dalaoli-shuxue/">https://zhuanlan.zhihu.com/dalaoli-shuxue/</a>

电邮：dalaoliliaoshuxue@gmail.com