---
title: '幂次数的“社交距离”有多大？—— 卡塔兰猜想'
date: "2021-10-02"
categories:
  - "每周一题"
---

这次聊一个数论里的著名猜想——“卡塔兰猜想”（Catalan's Conjecture）。其实它已经被证明了，它的名字现在应该叫做“米哈伊列斯库定理”才对。但无奈“卡塔兰猜想”的名字太著名了，用了太久了，所以没有人会用“米哈伊列斯库定理”这个名字。就像人们只知道“费马大定理”，而不会叫它“怀尔斯定理”。

卡塔兰猜想是比利时数学家欧仁·查理·卡塔兰在1844年提出的一个猜想：

方程：$x^p-y^q=1$

其中x, y, p, q都是正整数，p, q大于1，

只有$3^2-2^3=1$ 这样一组非平凡解。

这个猜想用一种直观的描述就是：请你把自然数中幂次形式的数，也就是可以表示成$a^b$ 形式的数都列出来，其中a, b都是自然数，且指数b>1。那么自然数中符合这个条件的有：

1, 4, 8，9, 16, 25, 27, 32, 64......

现在问所有这些数字中，有没有连续的两个整数？以上已经列出来一对：8和9是连续，但后面还有没有这样连续的两个幂次数呢？卡塔兰猜想就是说：除了8和9这一对之外，再也没有连续的都是幂次形式的自然数了。

这个命题的内容简单到小学生都可以理解。但一般来说，数论里这种小学生都可以理解的命题都是特别难的。

那来看一下这个问题被解决的历史过程吧。其实早在卡塔兰提出这个猜想的500年前，法国中世纪的犹太哲学家，吉尔松尼德（Levi ben Gerson，1288 - 1344）就证明了卡塔兰猜想的一个最简单的特例：两个完全平方数和完全立方数之间，只有8和9是相差1的，再也没有其他的了。

但是吉尔松尼德的证明当时并不为人知，所以后来欧拉又证明了同样的结论。欧拉的证明是比较复杂的，后来人们找到了相对简单的证明。我简单说说这个证明的思路。

还是回到原来的不定方程，现在我们只考虑完全立方数和完全平方数之间的情况，那么方程就便成为：

$x^3-y^2=\pm 1$

其中最简单的情况是右边等于1的情况，也就是：

$x^3-y^2=1$

这个方程，我们要证明它没有正整数解。证明第一步，我们把它改写成：

$x^3=y^2+1$

然后我们要对右边进行因式分解。虽然右边的$y^2+1$ ，在中学数学课本里是无法因式分解的，但是如果你听过大老李的节目，知道有“高斯整数”这个东西，那么$y^2+1$就可以分解为：

$x^3=(y+i)(y-i)$

其实，这是最关键的一步！虽然我们是在通常的整数范围内提出的问题，但是证明过程中，我们要跳入到“高斯整数”这个更大的“宇宙”中去。因为我们知道，如果原方程有正整数解，那么那些解也同样满足高斯整数条件下的命题。因为高斯整数包含所有整数，所以我们把$y^2+1$分解成$(y+i)(y-i)$是没有任何问题。

一旦右边进行了因式分解，那么问题就迎刃而解。你所需要分析的是$y+i$ 和$y-i$两个数的最大公约数。你会发现，这个最大公约数必须是2的因子，也就是它只可能是2或者1。

但另一方面，因为$y^2\equiv 0 \ \mbox{or}\  1 (\bmod 4)$，$y^2+1\equiv 1 \ \mbox{or}\  2 (\bmod 4)$。

对任何偶数，其3次方必然整除4，所以$x$只能是奇数，则$y+i$和$y-i$ 的最大公约数只是1，也就是$y+i$和$y-i$ 互质。

但要注意的是，在高斯整数中，“互质”表示这两个数的公因子为$\pm 1$和$\pm i$，这四种情况之一。还要注意，以上分析中用到一个重要前提是：“高斯整数”具有“唯一因子分解定理”。如果没有这个性质，那么很多讨论就进行不下去的。

既然$y+i$和$y-i$ 互质，意味着$y+i$和$y-i$本身必须是一个完全立方数，即:

$y+i=d(a+bi)^3$

其中a、b是整数，$d$ 是$\pm 1$ 、$\pm i$之一。因为$d^3$ 总是高斯整数下的一个单位元(unit)，所以$d$基本可以忽略， 于是：

$y+i=(a+bi)^3$

展开后，比较等式左右两边的实部和虚部。可以解得唯一解y=0（x=1），于是方程$x^3-y^2=1$没有正整数解。

对另一种情况：$x^3-y^2=-1$ ，需要证明它除了$x=2$和$y=3$以外，没有其他正整数解。第一步还是如法炮制，因式分解：

$x^3=(y+1)(y-1)$

这次同样可以确定$y+1$ 和$y-1$ 的最大公因子不是2就是1。虽然到这里的步骤，是大家应该很习惯的，但后面的讨论过程其实要比之前的高斯整数下的分析麻烦些，用到的准备知识会多一些，所以这里就不详述了。

以上就是现代数学中，对证明$x^3-y^2=\pm 1$这个方程，仅有$x=2$ 和$y=3$基本过程。以上就是卡塔兰猜想最简单的一个特例。

下一个突破是1850年，勒贝格证明了$x^p-y^2=1$这个方程无整数解（要注意，他不是发明”勒贝格积分“的那个勒贝格，只是同一个姓）。勒贝格的证明第一步其实与之前还是一样，把方程分解为：$x^p=(y+i)(y-i)$ 。

再下一个突破要经过的时间就很长了。过了111年，到1961年，中国数学家柯召(1910年4月12日～2002年11月8日)证明了，如果$x^2-y^p=1$有解，那么$x$要大于$10^{3\cdot 10^{9}}$，这样一个非常大的数字。

再到1976年，美国的Joseph E.Z. Chein去掉了这个下界，最终证明了$x^2-y^q=1$这个方程在$q>3$的时候无解。

但以上只是固定了一个幂次为完全平方数的情况，距离卡塔兰猜想还有相当大的距离。1999年, M. Mignotte 证明如果还有其他解，那么两个指数都有上界：

$p<7.15 \times 10^{11}$

$q<7.78 \times 10^{16}$

但两个指数还是太大，远超计算机可以枚举的范围。

终于到2002年，罗马尼亚数学家普雷达·米哈伊列斯库（Preda Mihăilescu, 1955 - ）最终完成了卡塔兰猜想的证明，从而解决了这个有150多年历史的猜想。他的证明的核心技术是环理论的“零化子”（annihilator），当然也是基于前人的成果。因为之前有人证明，如果卡塔兰猜想还有其他解，那么两个指数必须是某种特殊形式的质数对（Double Wieferich Prime Pair）。米哈伊列斯库证明，即使指数是这种形式的质数对，也无解，所以完成了证明。

以上介绍了”卡坦兰猜想“的历史，我知道你很想看看它的扩展。你能想到的第一个扩展大概是，两个幂次相差2的情况，之前列举过程中我们就看到了一组解是25和27。那有没有其他解？我是没找到。

但一个直观感觉是幂次数之间的距离总体上是逐渐增加的，所以现在数学家猜想：$x^p-y^q=m$，$m$是任何正整数，这个方程只有有限多的整数解。这是目前的一个猜想。而如果”ABC猜想“为真，这个猜想也为真。

卡塔兰猜想的另一个更有意思的扩展叫“费马--卡塔兰猜想”。它有点像费马大定理和卡塔兰猜想的结合体。费马大定理说$x^p+y^p=z^p$，指数大于等于3的情况下无解。那么允许指数不同的情况下，解的情况为何？或者说，更一般的情况下，对方程：

$x^p+y^q=z^r$

非平凡正整数解的情况如何？

数学家注意到一个情况是，如果三个指数都比较小的情况下，解是很多的。比如三个指数都是2，那就是勾股定理嘛。而如果三个指数要求比较大，解就少很多。特别是，如果要求三个指数的倒数和小于1的话，解的情况非常有意思。

目前已知，在$\frac{1}{p}+\frac{1}{q}+\frac{1}{r}<1$ 的情况下，对以上方程，现在找到以下10组解：

$1^{p}+2^{3}=3^{2}$
其中p>6；

$2^{5}+7^{2} =3^{4}$

$7^{3}+13^{2} =2^{9}$

$2^{7}+17^{3} =71^{2}$

$3^{5}+11^{4} =122^{2}$

$17^{7}+76271^{3} =21063928^{2}$

$1414^{3}+2213459^{2} =65^{7}$

$9262^{3}+15312283^{2} =113^{7}$

$43^{8}+96222^{3} =30042907^{2}$

$33^{8}+1549034^{2} =15613^{3}$

那么费马——卡塔兰猜想就是说，除了以上10组解，这个方程没有其他解。这是一个神奇的现象，对我来说这10组解看上去都是些奇奇怪怪的数字。数学里这种出现若干特别数字特例的情况是非常少的。我不太清楚数学家如何找到这10组解的，反正对我来说这10组解太有神秘感了。

而观察上面的10组解的话，你会发现，任何一组解里都有一个指数为2的数，也就是会出现完全平方数。由此出现一个”Beal猜想“，称：

以上方程在指数都大于2的情况下，无（非平凡）解。

Beal是美国的银行家，也是数学爱好者。他出资悬赏100万美元，证明这个猜想。当然，这个猜想与费马——卡塔兰猜想谁更难，是见仁见智了。如果你要找反例的话，那么Beal猜想更难，因为它要求反例中的指数都大于2。如果是证明猜想为真的话，那么”Beal猜想“稍微简单点。因为如果”费马——卡塔兰猜想“为真，就蕴含了Beal猜想为真，反之不然。

以上猜想还能扩展到高斯整数范围内，还有一些神奇数字。比如，对原版”卡塔兰猜想“，高斯整数中有一组解：

$(78+78 i)^{2}-(-23 i)^{3}=i$

对，”费马——卡坦兰猜想“，高斯整数内也有若干解，比如：

$(8+5 i)^{2}+(5+3 i)^{3}=(1+2 i)^{7}$

$(20+9 i)^{2}+(1+8 i)^{3}=(1+i)^{15}$

对，Beal猜想，高斯整数中找到一个反例：

$(-2+i)^3 + (-2-i)^3 = (1+i)^4$

当然这些解怎么找，是不是全部解，这些问题就太难了。

好了，今天关于卡塔兰猜想的问题就聊到这里，最大感想还是数论的深不可测。而高斯整数在这些问题中非常有用，更加验证了“虚数不虚”。

参考链接：

https://mathworld.wolfram.com/Fermat-CatalanConjecture.html

https://mathworld.wolfram.com/CatalansConjecture.html

https://www.mathpuzzle.com/Gaussians.html